name: Build SpearX macOS & Windows

on:
  workflow_dispatch:

jobs:
  macos-build-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Clone remote Spear
        run: git clone https://github.com/sspsec/Spear.git

      - name: Install frontend deps
        run: |
          cd "Spear/Spear X/frontend"
          npm ci

      - name: Build macOS
        run: |
          cd "Spear/Spear X"
          wails build -platform darwin/arm64  -o build/bin/SpearX-macos-arm64
      - name: 查看构建目录内容
        run: |
          ls -al "Spear/Spear X/build/bin/"
          mv "Spear/Spear X/build/bin/SpearX.app" "Spear/Spear X/build/bin/SpearX-macos-arm64.app"
          ls -al "Spear/Spear X/build/bin/"

       

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SpearX-macos
          path: |
            "Spear/Spear X/build/bin/SpearX-macos-arm64"
            
  macos-build-amd64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Clone remote Spear
        run: git clone https://github.com/sspsec/Spear.git

      - name: Install frontend deps
        run: |
          cd "Spear/Spear X/frontend"
          npm ci

      - name: Build macOS
        run: |
          cd "Spear/Spear X"
          wails build -platform darwin/amd64  -o build/bin/SpearX-macos-amd64
      - name: 查看构建目录内容
        run: |
          ls -al "Spear/Spear X/build/bin/"
          mv "Spear/Spear X/build/bin/SpearX.app" "Spear/Spear X/build/bin/SpearX-macos-amd64.app"
          ls -al "Spear/Spear X/build/bin/"

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SpearX-macos
          path: |
            "Spear/Spear X/build/bin/SpearX-macos-amd64"
           

  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Install Wails CLI
        shell: pwsh
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Clone remote Spear
        run: git clone https://github.com/sspsec/Spear.git
      - name: Install frontend deps
        shell: pwsh
        run: |
          cd "Spear/Spear X/frontend"
          npm ci

      - name: Build Windows
        shell: pwsh
        run: |
          cd "Spear/Spear X"
          wails build -platform windows/amd64 -o build/bin/SpearX-windows.exe

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: SpearX-windows
          path: "Spear/Spear X/build/bin/*"
