name: Build SpearX All Platforms

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 安装 Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      # 2. 安装 Wails CLI
      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # 3. 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 4. 克隆仓库
      - name: Clone Spear
        run: git clone https://github.com/sspsec/Spear.git

      # 5. 安装前端依赖
      - name: Install frontend deps
        run: |
          cd Spear
          cd 'Spear X'
          cd frontend
          npm install

      # 6. 多平台构建
      - name: Build for all platforms
        run: |
          cd Spear
          cd 'Spear X'
          wails build -platform darwin/arm64
          wails build -platform darwin/amd64
          wails build -platform windows/amd64
          

      # 7. 输出产物（可选）
      - name: Build for all platforms
        run: |
          cd Spear
          cd 'Spear X'
          wails build -platform darwin/arm64  -o build/bin/SpearX-macos-arm64
          wails build -platform darwin/amd64  -o build/bin/SpearX-macos-amd64
          wails build -platform windows/amd64 -o build/bin/SpearX-windows.exe
          wails build -platform linux/amd64   -o build/bin/SpearX-linux

          

      # 8. 打包并上传所有产物
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SpearX-all-platforms
          path: Spear/Spear X/build/bin/*
